using System;
using System.Collections.Generic;

namespace IFFCO.TECHPROD.Web.Models
{
    public partial class DailytechOutput
    {
        public DateTime DataDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? CreationDatetime { get; set; }
        public decimal? A1506 { get; set; }
        public decimal? A1507 { get; set; }
        public decimal? A1508 { get; set; }
        public decimal? A1509 { get; set; }
        public decimal? A1511 { get; set; }
        public decimal? A1512 { get; set; }
        public decimal? A1513 { get; set; }
        public decimal? A1514 { get; set; }
        public decimal? A1515 { get; set; }
        public decimal? A1516 { get; set; }
        public decimal? A1517 { get; set; }
        public decimal? A1518 { get; set; }
        public decimal? A1519 { get; set; }
        public decimal? A1520 { get; set; }
        public decimal? A1521 { get; set; }
        public decimal? A1522 { get; set; }
        public decimal? A1538 { get; set; }
        public decimal? A1540 { get; set; }
        public decimal? A1541 { get; set; }
        public decimal? A1542 { get; set; }
        public decimal? A1543 { get; set; }
        public decimal? A1544 { get; set; }
        public decimal? A1545 { get; set; }
        public decimal? A1546 { get; set; }
        public decimal? A1547 { get; set; }
        public decimal? A1548 { get; set; }
        public decimal? A1549 { get; set; }
        public decimal? A1550 { get; set; }
        public decimal? A2506 { get; set; }
        public decimal? A2507 { get; set; }
        public decimal? A2508 { get; set; }
        public decimal? A2509 { get; set; }
        public decimal? A2511 { get; set; }
        public decimal? A2517 { get; set; }
        public decimal? A2518 { get; set; }
        public decimal? A2519 { get; set; }
        public decimal? A2520 { get; set; }
        public decimal? A2521 { get; set; }
        public decimal? A2522 { get; set; }
        public decimal? A2523 { get; set; }
        public decimal? A2524 { get; set; }
        public decimal? A2527 { get; set; }
        public decimal? A2528 { get; set; }
        public decimal? A2529 { get; set; }
        public decimal? A2530 { get; set; }
        public decimal? A2532 { get; set; }
        public decimal? A2551 { get; set; }
        public decimal? A2554 { get; set; }
        public decimal? A2555 { get; set; }
        public decimal? A2556 { get; set; }
        public decimal? A2557 { get; set; }
        public decimal? A2558 { get; set; }
        public decimal? A2559 { get; set; }
        public decimal? A2560 { get; set; }
        public decimal? A2561 { get; set; }
        public decimal? A2562 { get; set; }
        public decimal? A2563 { get; set; }
        public decimal? A2564 { get; set; }
        public decimal? A2565 { get; set; }
        public decimal? A2567 { get; set; }
        public decimal? A1552 { get; set; }
        public decimal? U1501 { get; set; }
        public decimal? U1502 { get; set; }
        public decimal? U1503 { get; set; }
        public decimal? U1504 { get; set; }
        public decimal? U1505 { get; set; }
        public decimal? U1506 { get; set; }
        public decimal? U1507 { get; set; }
        public decimal? U1508 { get; set; }
        public decimal? U1509 { get; set; }
        public decimal? U1512 { get; set; }
        public decimal? U1516 { get; set; }
        public decimal? U1517 { get; set; }
        public decimal? U1519 { get; set; }
        public decimal? U1520 { get; set; }
        public decimal? U1521 { get; set; }
        public decimal? U1522 { get; set; }
        public decimal? U1523 { get; set; }
        public decimal? U1524 { get; set; }
        public decimal? U1525 { get; set; }
        public decimal? U1526 { get; set; }
        public decimal? U1527 { get; set; }
        public decimal? U1528 { get; set; }
        public decimal? U1529 { get; set; }
        public decimal? U1530 { get; set; }
        public decimal? U1531 { get; set; }
        public decimal? U1532 { get; set; }
        public decimal? U1533 { get; set; }
        public decimal? U1536 { get; set; }
        public decimal? U1537 { get; set; }
        public decimal? U1538 { get; set; }
        public decimal? U1539 { get; set; }
        public decimal? U1540 { get; set; }
        public decimal? U1541 { get; set; }
        public decimal? U1543 { get; set; }
        public decimal? U1544 { get; set; }
        public decimal? U2501 { get; set; }
        public decimal? U2502 { get; set; }
        public decimal? U2503 { get; set; }
        public decimal? U2504 { get; set; }
        public decimal? U2505 { get; set; }
        public decimal? U2506 { get; set; }
        public decimal? U2507 { get; set; }
        public decimal? U2508 { get; set; }
        public decimal? U2509 { get; set; }
        public decimal? U2510 { get; set; }
        public decimal? U2513 { get; set; }
        public decimal? U2519 { get; set; }
        public decimal? U2520 { get; set; }
        public decimal? U2521 { get; set; }
        public decimal? U2522 { get; set; }
        public decimal? U2523 { get; set; }
        public decimal? U2524 { get; set; }
        public decimal? U2525 { get; set; }
        public decimal? U2526 { get; set; }
        public decimal? U2527 { get; set; }
        public decimal? U2528 { get; set; }
        public decimal? U2529 { get; set; }
        public decimal? U2530 { get; set; }
        public decimal? U2531 { get; set; }
        public decimal? U2532 { get; set; }
        public decimal? U2533 { get; set; }
        public decimal? U2534 { get; set; }
        public decimal? U2535 { get; set; }
        public decimal? U2537 { get; set; }
        public decimal? U2538 { get; set; }
        public decimal? U2540 { get; set; }
        public decimal? U2541 { get; set; }
        public decimal? U2543 { get; set; }
        public decimal? Sb01 { get; set; }
        public decimal? Sb02 { get; set; }
        public decimal? Sb03 { get; set; }
        public decimal? Sb04 { get; set; }
        public decimal? Sb06 { get; set; }
        public decimal? Sb07 { get; set; }
        public decimal? Sb08 { get; set; }
        public decimal? Sb09 { get; set; }
        public decimal? Sb11 { get; set; }
        public decimal? Sb12 { get; set; }
        public decimal? Sb13 { get; set; }
        public decimal? Sb14 { get; set; }
        public decimal? Sb15 { get; set; }
        public decimal? Sb18 { get; set; }
        public decimal? Sb19 { get; set; }
        public decimal? Sb20 { get; set; }
        public decimal? Sb21 { get; set; }
        public decimal? Sb22 { get; set; }
        public decimal? Sg503 { get; set; }
        public decimal? Sg504 { get; set; }
        public decimal? Sg508 { get; set; }
        public decimal? Sg509 { get; set; }
        public decimal? Sg510 { get; set; }
        public decimal? Sg511 { get; set; }
        public decimal? Sg512 { get; set; }
        public decimal? Sg514 { get; set; }
        public decimal? Sg515 { get; set; }
        public decimal? Sg517 { get; set; }
        public decimal? Sg522 { get; set; }
        public decimal? Sg524 { get; set; }
        public decimal? Sg525 { get; set; }
        public decimal? Sg527 { get; set; }
        public decimal? Sg528 { get; set; }
        public decimal? Sg529 { get; set; }
        public decimal? Sg530 { get; set; }
        public decimal? Sg531 { get; set; }
        public decimal? Sg533 { get; set; }
        public decimal? Sg534 { get; set; }
        public decimal? Sg535 { get; set; }
        public decimal? Sg541 { get; set; }
        public decimal? Sg542 { get; set; }
        public decimal? Sg543 { get; set; }
        public decimal? Sg544 { get; set; }
        public decimal? Sg545 { get; set; }
        public decimal? Sg546 { get; set; }
        public decimal? Sg547 { get; set; }
        public decimal? Sg548 { get; set; }
        public decimal? Sg549 { get; set; }
        public decimal? Sg550 { get; set; }
        public decimal? Sg560 { get; set; }
        public decimal? Os504 { get; set; }
        public decimal? Os505 { get; set; }
        public decimal? Os506 { get; set; }
        public decimal? Os509 { get; set; }
        public decimal? Os512 { get; set; }
        public decimal? Os514 { get; set; }
        public decimal? Os521 { get; set; }
        public decimal? Os523 { get; set; }
        public decimal? Os524 { get; set; }
        public decimal? Os525 { get; set; }
        public decimal? Os526 { get; set; }
        public decimal? Os533 { get; set; }
        public decimal? Os535 { get; set; }
        public decimal? Os536 { get; set; }
        public decimal? Os537 { get; set; }
        public decimal? Os538 { get; set; }
        public decimal? Os545 { get; set; }
        public decimal? Os547 { get; set; }
        public decimal? Os548 { get; set; }
        public decimal? Os549 { get; set; }
        public decimal? Os550 { get; set; }
        public decimal? Os551 { get; set; }
        public decimal? Os552 { get; set; }
        public decimal? Os553 { get; set; }
        public decimal? Os554 { get; set; }
        public decimal? Os555 { get; set; }
        public decimal? Os556 { get; set; }
        public decimal? Os557 { get; set; }
        public decimal? Os558 { get; set; }
        public decimal? Os559 { get; set; }
        public decimal? Os560 { get; set; }
        public decimal? Os561 { get; set; }
        public decimal? Os562 { get; set; }
        public decimal? Os563 { get; set; }
        public decimal? Os564 { get; set; }
        public decimal? Os565 { get; set; }
        public decimal? Os566 { get; set; }
        public decimal? Ph1523 { get; set; }
        public decimal? Ph1525 { get; set; }
        public decimal? Ph1528 { get; set; }
        public decimal? Ph1529 { get; set; }
        public decimal? Ph1530 { get; set; }
        public decimal? Ph1531 { get; set; }
        public decimal? Ph1532 { get; set; }
        public decimal? Ph1533 { get; set; }
        public decimal? Ph1534 { get; set; }
        public decimal? Ph1535 { get; set; }
        public decimal? Ph1536 { get; set; }
        public decimal? Ph1537 { get; set; }
        public decimal? Ph1538 { get; set; }
        public decimal? Ph1539 { get; set; }
        public decimal? Ph2523 { get; set; }
        public decimal? Ph2525 { get; set; }
        public decimal? Ph2528 { get; set; }
        public decimal? Ph2529 { get; set; }
        public decimal? Ph2530 { get; set; }
        public decimal? Ph2531 { get; set; }
        public decimal? Ph2532 { get; set; }
        public decimal? Ph2533 { get; set; }
        public decimal? Ph2534 { get; set; }
        public decimal? Ph2535 { get; set; }
        public decimal? Ph2536 { get; set; }
        public decimal? Ph2537 { get; set; }
        public decimal? Ph2538 { get; set; }
        public decimal? Ph2539 { get; set; }
        public decimal? Tp504 { get; set; }
        public decimal? Tp505 { get; set; }
        public decimal? Tp506 { get; set; }
        public decimal? Tp507 { get; set; }
        public decimal? Tp508 { get; set; }
        public decimal? Tp509 { get; set; }
        public decimal? Tp510 { get; set; }
        public decimal? Tp511 { get; set; }
        public decimal? Tp512 { get; set; }
        public decimal? Tp513 { get; set; }
        public decimal? Tp514 { get; set; }
        public decimal? Tp515 { get; set; }
        public decimal? Tp516 { get; set; }
        public decimal? Tp517 { get; set; }
        public decimal? Tp518 { get; set; }
        public decimal? Tp519 { get; set; }
        public decimal? Tp520 { get; set; }
        public decimal? Tp521 { get; set; }
        public decimal? Tp522 { get; set; }
        public decimal? Tp523 { get; set; }
        public decimal? Tp524 { get; set; }
        public decimal? Tp525 { get; set; }
        public decimal? Tp526 { get; set; }
        public decimal? Tp527 { get; set; }
        public decimal? Tp528 { get; set; }
        public decimal? Tp529 { get; set; }
        public decimal? Tp530 { get; set; }
        public decimal? Tp531 { get; set; }
        public decimal? Tp532 { get; set; }
        public decimal? Tp533 { get; set; }
        public decimal? Tp534 { get; set; }
        public decimal? Tp535 { get; set; }
        public decimal? Tp536 { get; set; }
        public decimal? Tp537 { get; set; }
        public decimal? Tp538 { get; set; }
        public decimal? Tp539 { get; set; }
        public decimal? Tp540 { get; set; }
        public decimal? Tp501 { get; set; }
        public decimal? Tp502 { get; set; }
        public decimal? Tp503 { get; set; }
        public decimal? Os508 { get; set; }
        public decimal? Os511 { get; set; }
        public decimal? Os517 { get; set; }
        public decimal? Os515 { get; set; }
        public decimal? A1501 { get; set; }
        public decimal? A2502 { get; set; }
        public decimal? Os501 { get; set; }
        public double? Ng { get; set; }
        public double? Pmtg { get; set; }
        public double? Rlng { get; set; }
        public double? Srlng { get; set; }
        public double? Islng { get; set; }
        public decimal? A1524 { get; set; }
        public decimal? A1525 { get; set; }
        public decimal? A2535 { get; set; }
        public decimal? A2536 { get; set; }
        public double? Flng { get; set; }
        public decimal? A1568 { get; set; }
        public decimal? A1569 { get; set; }
        public decimal? A1570 { get; set; }
        public int? U1545 { get; set; }
        public int? U2544 { get; set; }
        public double? Slng { get; set; }
        public double? Gspcl { get; set; }
        public double? Fislng { get; set; }
        public double? Spmtg { get; set; }
        public decimal? Imgspcl { get; set; }
        public decimal? A2582 { get; set; }
        public decimal? A1571 { get; set; }
        public decimal? A1572 { get; set; }
        public decimal? OldIslng { get; set; }
        public double? U1504n { get; set; }
        public double? U1504nm { get; set; }
        public double? U1505n { get; set; }
        public double? U1505nm { get; set; }
        public double? U1506n { get; set; }
        public double? U1506nm { get; set; }
        public double? U1507n { get; set; }
        public double? U1507nm { get; set; }
        public double? U1508n { get; set; }
        public double? U1508nm { get; set; }
        public double? U1509n { get; set; }
        public double? U1509nm { get; set; }
        public double? U1522n { get; set; }
        public double? U1522nm { get; set; }
        public double? U1523n { get; set; }
        public double? U1523nm { get; set; }
        public double? U1524n { get; set; }
        public double? U1524nm { get; set; }
        public double? U1525n { get; set; }
        public double? U1525nm { get; set; }
        public double? U1526n { get; set; }
        public double? U1526nm { get; set; }
        public double? U1530n { get; set; }
        public double? U1530nm { get; set; }
        public double? U1527n { get; set; }
        public double? U1527nm { get; set; }
        public double? U1541n { get; set; }
        public double? U1541nm { get; set; }
        public double? U2503n { get; set; }
        public double? U2503nm { get; set; }
        public decimal? U2504n { get; set; }
        public decimal? U2504nm { get; set; }
        public decimal? U2505n { get; set; }
        public decimal? U2505nm { get; set; }
        public decimal? U2506n { get; set; }
        public decimal? U2506nm { get; set; }
        public decimal? U2507n { get; set; }
        public decimal? U2507nm { get; set; }
        public decimal? U2508n { get; set; }
        public decimal? U2508nm { get; set; }
        public decimal? U2509n { get; set; }
        public decimal? U2509nm { get; set; }
        public decimal? U2510n { get; set; }
        public decimal? U2510nm { get; set; }
        public decimal? U2532n { get; set; }
        public decimal? U2532nm { get; set; }
        public decimal? U2533n { get; set; }
        public decimal? U2533nm { get; set; }
        public decimal? U2534n { get; set; }
        public decimal? U2534nm { get; set; }
        public decimal? U2530n { get; set; }
        public decimal? U2530nm { get; set; }
        public decimal? U2531n { get; set; }
        public decimal? U2531nm { get; set; }
        public decimal? U2526n { get; set; }
        public decimal? U2526nm { get; set; }
        public decimal? U2527n { get; set; }
        public decimal? U2527nm { get; set; }
        public decimal? U2528n { get; set; }
        public decimal? U2528nm { get; set; }
        public decimal? U2529n { get; set; }
        public decimal? U2529nm { get; set; }
        public decimal? U1550 { get; set; }
        public decimal? U1551 { get; set; }
        public decimal? U1552 { get; set; }
        public decimal? U1553 { get; set; }
        public decimal? U1555 { get; set; }
        public decimal? U2550 { get; set; }
        public decimal? U2551 { get; set; }
        public decimal? U2552 { get; set; }
        public decimal? U2553 { get; set; }
        public decimal? U2555 { get; set; }
        public decimal? Tp501n { get; set; }
        public decimal? Tp501nm { get; set; }
        public decimal? Tp502n { get; set; }
        public decimal? Tp502nm { get; set; }
        public decimal? Tp503n { get; set; }
        public decimal? Tp503nm { get; set; }
        public decimal? Tp504n { get; set; }
        public decimal? Tp504nm { get; set; }
        public decimal? Tp505n { get; set; }
        public decimal? Tp505nm { get; set; }
        public decimal? Tp506n { get; set; }
        public decimal? Tp506nm { get; set; }
        public decimal? Tp507n { get; set; }
        public decimal? Tp507nm { get; set; }
        public decimal? Tp508n { get; set; }
        public decimal? Tp508nm { get; set; }
        public decimal? Tp509n { get; set; }
        public decimal? Tp509nm { get; set; }
        public decimal? Tp510n { get; set; }
        public decimal? Tp510nm { get; set; }
        public decimal? Tp515n { get; set; }
        public decimal? Tp515nm { get; set; }
        public decimal? Tp516n { get; set; }
        public decimal? Tp516nm { get; set; }
        public decimal? Tp517n { get; set; }
        public decimal? Tp517nm { get; set; }
        public decimal? Tp518n { get; set; }
        public decimal? Tp518nm { get; set; }
        public decimal? Tp519n { get; set; }
        public decimal? Tp519nm { get; set; }
        public decimal? Tp520n { get; set; }
        public decimal? Tp520nm { get; set; }
        public decimal? Tp521n { get; set; }
        public decimal? Tp521nm { get; set; }
        public decimal? Tp522n { get; set; }
        public decimal? Tp522nm { get; set; }
        public decimal? Tp523n { get; set; }
        public decimal? Tp523nm { get; set; }
        public decimal? Tp524n { get; set; }
        public decimal? Tp524nm { get; set; }
        public decimal? Tp525n { get; set; }
        public decimal? Tp525nm { get; set; }
        public decimal? Tp526n { get; set; }
        public decimal? Tp526nm { get; set; }
        public decimal? Tp527n { get; set; }
        public decimal? Tp527nm { get; set; }
        public decimal? Tp528n { get; set; }
        public decimal? Tp528nm { get; set; }
        public decimal? Tp529n { get; set; }
        public decimal? Tp529nm { get; set; }
        public decimal? Tp530n { get; set; }
        public decimal? Tp530nm { get; set; }
        public decimal? Tp531n { get; set; }
        public decimal? Tp531nm { get; set; }
        public decimal? Tp532n { get; set; }
        public decimal? Tp532nm { get; set; }
        public decimal? Tp533n { get; set; }
        public decimal? Tp533nm { get; set; }
        public decimal? Tp534n { get; set; }
        public decimal? Tp534nm { get; set; }
        public decimal? Tp535n { get; set; }
        public decimal? Tp535nm { get; set; }
        public decimal? Tp536n { get; set; }
        public decimal? Tp536nm { get; set; }
        public decimal? Ph1532nm { get; set; }
        public decimal? Ph1533nm { get; set; }
        public decimal? Ph1534nm { get; set; }
        public decimal? Ph1536nm { get; set; }
        public decimal? Ph1538nm { get; set; }
        public decimal? Ph2532nm { get; set; }
        public decimal? Ph2533nm { get; set; }
        public decimal? Ph2534nm { get; set; }
        public decimal? Ph2536nm { get; set; }
        public decimal? Ph2538nm { get; set; }
        public decimal? Ph1523nm { get; set; }
        public decimal? Ph2523nm { get; set; }
        public decimal? Ph1528nm { get; set; }
        public decimal? Ph2528nm { get; set; }
        public decimal? U1549 { get; set; }
        public decimal? Ph1523pp { get; set; }
        public decimal? Ph1528pp { get; set; }
        public decimal? Ph1534pp { get; set; }
        public decimal? Ph1536pp { get; set; }
        public decimal? Ph1538pp { get; set; }
        public decimal? Ph2523pp { get; set; }
        public decimal? Ph2528pp { get; set; }
        public decimal? Ph2534pp { get; set; }
        public decimal? Ph2536pp { get; set; }
        public decimal? Ph2538pp { get; set; }
        public decimal? Ph2523p45 { get; set; }
        public decimal? Ph2528p45 { get; set; }
        public decimal? Ph2534p45 { get; set; }
        public decimal? Ph2536p45 { get; set; }
        public decimal? Ph2538p45 { get; set; }
        public decimal? Ph1523p45 { get; set; }
        public decimal? Ph1528p45 { get; set; }
        public decimal? Ph1534p45 { get; set; }
        public decimal? Ph1536p45 { get; set; }
        public decimal? Ph1538p45 { get; set; }
        public decimal? Tp502nm45 { get; set; }
        public decimal? Tp503nm45 { get; set; }
        public decimal? Tp504nm45 { get; set; }
        public decimal? Tp505nm45 { get; set; }
        public decimal? Tp506nm45 { get; set; }
        public decimal? Tp507nm45 { get; set; }
        public decimal? Tp508nm45 { get; set; }
        public decimal? Tp509nm45 { get; set; }
        public decimal? Tp510nm45 { get; set; }
        public decimal? Tp515nm45 { get; set; }
        public decimal? Tp516nm45 { get; set; }
        public decimal? Tp517nm45 { get; set; }
        public decimal? Tp518nm45 { get; set; }
        public decimal? Tp519nm45 { get; set; }
        public decimal? Tp520nm45 { get; set; }
        public decimal? Tp521nm45 { get; set; }
        public decimal? Tp522nm45 { get; set; }
        public decimal? Tp523nm45 { get; set; }
        public decimal? Tp524nm45 { get; set; }
        public decimal? Tp525nm45 { get; set; }
        public decimal? Tp526nm45 { get; set; }
        public decimal? Tp527nm45 { get; set; }
        public decimal? Tp528nm45 { get; set; }
        public decimal? Tp529nm45 { get; set; }
        public decimal? Tp530nm45 { get; set; }
        public decimal? Tp531nm45 { get; set; }
        public decimal? Tp532nm45 { get; set; }
        public decimal? Tp533nm45 { get; set; }
        public decimal? Tp534nm45 { get; set; }
        public decimal? Tp535nm45 { get; set; }
        public decimal? Tp536nm45 { get; set; }
        public decimal? Tp501nm45 { get; set; }
        public decimal? Ph1623 { get; set; }
        public decimal? Ph1628 { get; set; }
        public decimal? Ph1634 { get; set; }
        public decimal? Ph1636 { get; set; }
        public decimal? Ph1638 { get; set; }
        public decimal? Ph2623 { get; set; }
        public decimal? Ph2628 { get; set; }
        public decimal? Ph2634 { get; set; }
        public decimal? Ph2636 { get; set; }
        public decimal? Ph2638 { get; set; }
    }
}
